spring:
  application:
    name: auction-management-backend

  datasource:
    url: jdbc:postgresql://localhost:5433/auction_ai
    username: postgres
    password: welcome
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true